import { Interface } from "readline";
import { IDataItem } from "./src/store/reducers/data";

export type TData = {
  name: string;
  rus: string[];
  de: string[];
};
export type TBazaArrayItem = Array<[string, IDataItem]>;
export interface IWord {
  rus: string;
  de: string;
}

//// УГАДАЙ
export const Lesson1Quess: TData[] = [
  {
    name: "Дни недели",
    rus: [
      "Понедельник",
      "Вторник",
      "Среда",
      "Четверг",
      "Пятница",
      "Суббота",
      "Воскресенье",
    ],
    de: [
      "Montag",
      "Dienstag",
      "Mittwoch",
      "Donnerstag",
      "Freitag",
      "Samstag",
      "Sonntag",
    ],
  },
  {
    name: "Дни",
    rus: ["Сегодня", "Завтра", "Послезавтра", "Вчера", "Позавчера"],
    de: ["Heute", "Morgen", "Übermorgen", "Gestern", "Vorgestern"],
  },
  {
    name: "Времена года",
    rus: ["Весна", "Лето", "Осень", "Зима"],
    de: ["Frühling", "Sommer", "Herbst", "Winter"],
  },
  {
    name: "Habe",
    rus: ["Ich", "Du", "Er/Sie/Es", "Wir", "Ihr", "Sie"],
    de: ["habe", "hast", "hat", "haben", "habt", "haben"],
  },
  {
    name: "Bist",
    rus: ["Ich", "Du", "Er/Sie/Es", "Wir", "Ihr", "Sie"],
    de: ["bin", "bist", "ist", "sind", "seid", "sind"],
  },
];

export const Lesson6Quess: TData[] = [
  {
    name: "Модальные глаголы",
    rus: [
      "мочь, иметь разрешение",
      "мочь, уметь",
      "быть обязанным",
      "быть должным",
      "хотеть, вежливая форма",
      "хотеть",
      "нравиться",
      "знать, помнить",
    ],
    de: [
      "Dürfen",
      "Können",
      "Sollen",
      "Müssen",
      "Möchten",
      "Wollen",
      "Mögen",
      "Wissen",
    ],
  },

  {
    name: "Dürfen - (мочь, иметь разрешение)",
    rus: ["Ich", "Du", "Er/Sie/Es", "Wir", "Ihr", "Sie"],
    de: ["darf", "darfst", "darf", "dürfen", "dürft", "dürfen"],
  },
  {
    name: "Können - (мочь, уметь)",
    rus: ["Ich", "Du", "Er/Sie/Es", "Wir", "Ihr", "Sie"],
    de: ["kann", "kannst", "kann", "können", "könnt", "können"],
  },
  {
    name: "Sollen - (быть обязанным)",
    rus: ["Ich", "Du", "Er/Sie/Es", "Wir", "Ihr", "Sie"],
    de: ["soll", "sollst", "soll", "sollen", "sollt", "sollen"],
  },
  {
    name: "Müssen - (быть должным)",
    rus: ["Ich", "Du", "Er/Sie/Es", "Wir", "Ihr", "Sie"],
    de: ["muss", "musst", "muss", "müssen", "müsst", "müssen"],
  },
  {
    name: "Möchten - (хотеть, вежливая форма)",
    rus: ["Ich", "Du", "Er/Sie/Es", "Wir", "Ihr", "Sie"],
    de: ["möchte", "möchtest", "möchte", "möchten", "möchtet", "möchten"],
  },
  {
    name: "Wollen - (хотеть)",
    rus: ["Ich", "Du", "Er/Sie/Es", "Wir", "Ihr", "Sie"],
    de: ["will", "willst", "will", "wollen", "wollt", "wollen"],
  },
  {
    name: "Mögen - (нравиться)",
    rus: ["Ich", "Du", "Er/Sie/Es", "Wir", "Ihr", "Sie"],
    de: ["mag", "magst", "mag", "mögen", "mögt", "mögen"],
  },
  {
    name: "Wissen - (знать, помнить)",
    rus: ["Ich", "Du", "Er/Sie/Es", "Wir", "Ihr", "Sie"],
    de: ["weiß", "weißt", "weiß", "wissen", "wisst", "wissen"],
  },
];

export const Lesson7Quess: TData[] = [
  {
    name: "Притяжательные местоимения",
    rus: ["мой / моя", "твой / твоя", "его", "её", "наш", "ваш", "их", "Ваш"],
    de: [
      "mein / meine",
      "dein / deine",
      "sein / seine",
      "ihr / ihre",
      "unser / unsere",
      "euer / eure",
      "ihr / ihre",
      "Ihr / Ihre",
    ],
  },
];

export const Lesson8Quess: TData[] = [
  {
    name: "Вопросы 1",
    rus: ["Что?", "Кто?", "Кого?", "Кому?", "Как?", "Где?", "Почему?"],
    de: ["Was?", "Wer?", "Wen?", "Wem?", "Wie?", "Wo?", "Warum?"],
  },

  {
    name: "Вопросы 2",
    rus: [
      "Когда?",
      "Откуда?",
      "Куда?",
      "Сколько? (как много)",
      "Сколько? (как долго)",
      "Чей?",
      "Какой?",
    ],
    de: [
      "Wann?",
      "Woher?",
      "Wohin?",
      "Wie viel?",
      "Wie lange?",
      "Wessen?",
      "Welcher?",
    ],
  },
];

//// СЛОВА
export const lesson1WordsArr: IWord[] = [
  { rus: "Мужчина. Муж.", de: "Der Mann" },
  { rus: "Женщина. Жена.", de: "Die Frau" },
  { rus: "Мальчик.", de: "Der Junge" },
  { rus: "Девочка.", de: "Das Mädchen" },
  { rus: "Ребенок.", de: "Das Kind" },
  { rus: "Отец.", de: "Der Vater" },
  { rus: "Мать.", de: "Die Mutter" },
  { rus: "Дедушка.", de: "Der Opa" },
  { rus: "Бабушка.", de: "Die Oma" },
  { rus: "Брат.", de: "Der Bruder" },
  { rus: "Сестра.", de: "Die Schwester" },
  { rus: "Собака.", de: "Der Hund" },
  { rus: "Кошка.", de: "Die Katze" },
  { rus: "Дом.", de: "Das Haus" },
  { rus: "Квартира.", de: "Die Wohnung" },
  { rus: "Комната.", de: "Das Zimmer" },
  { rus: "Машина.", de: "Das Auto" },
  { rus: "Корабль.", de: "Das Schiff" },
  { rus: "Велосипед.", de: "Das Fahrrad" },
  { rus: "Автобус.", de: "Der Bus" },
  { rus: "Книга.", de: "Das Buch" },
  { rus: "Фильм.", de: "Der Film" },
  { rus: "Хорошо.", de: "Gut" },
  { rus: "Плохо.", de: "Schlecht" },
  { rus: "Большой.", de: "Groß" },
  { rus: "Маленький.", de: "Klein" },
  { rus: "Молодой.", de: "Jung" },
  { rus: "Новый.", de: "Neu" },
  { rus: "Старый.", de: "Alt" },
  { rus: "Умный.", de: "Klug" },
  { rus: "Глупый.", de: "Dumm" },
  { rus: "Веселый.", de: "Lustig" },
  { rus: "Грустный.", de: "Traurig" },
  { rus: "Толстый.", de: "Dick" },
  { rus: "Худой, Тонкий.", de: "Dünn" },
  { rus: "Красивый.", de: "Schön" },
  { rus: "Высокий.", de: "Hoch" },
  { rus: "Низкий.", de: "Niedrig" },
  { rus: "Близко.", de: "Nah" },
  { rus: "Далеко.", de: "Weit" },
  { rus: "Быстро.", de: "Schnell" },
  { rus: "Медленно.", de: "Langsam" },
  { rus: "Интересно.", de: "Interessant" },
  { rus: "Скучно.", de: "Langweilig" },
  { rus: "Тяжело.", de: "Schwer" },
  { rus: "Сложно.", de: "Schwierig" },
  { rus: "Легко.", de: "Leicht" },
  { rus: "громко", de: "Laut" },
  { rus: "тихо", de: "Leise" },
  { rus: "много", de: "Viel" },
  { rus: "мало", de: "Wenig" },
  { rus: "дорого", de: "Teuer" },
  { rus: "дешево", de: "Billig" },
  { rus: "милый", de: "Nett" },
  { rus: "симпатичный", de: "Hübsch" },
  { rus: "сильный", de: "Stark" },
  { rus: "слабый", de: "Schwach" },
  { rus: "ужасный, страшный", de: "Hässlich" },
  { rus: "грязный", de: "Schmutzig" },
  { rus: "чистый", de: "Sauber" },
  { rus: "делать, заниматься", de: "Machen" },
  { rus: "играть", de: "Spielen" },
  { rus: "стоять", de: "Stehen" },
  { rus: "прыгать", de: "Springen" },
  { rus: "лежать", de: "Liegen" },
  { rus: "идти", de: "Gehen" },
  { rus: "сидеть", de: "Sitzen" },
  { rus: "танцевать", de: "Tanzen" },
  { rus: "слышать", de: "Hören" },
  { rus: "петь", de: "Singen" },
  { rus: "писать", de: "Schreiben" },
  { rus: "пить", de: "Trinken" },
  { rus: "заказывать", de: "Bestellen" },
  { rus: "покупать", de: "Kaufen" },
  { rus: "продавать", de: "Verkaufen" },
  { rus: "спрашивать", de: "Fragen" },
  { rus: "отвечать", de: "Antworten" },
  { rus: "получать", de: "Bekommen" },
  { rus: "есть, кушать", de: "essen" },
  { rus: "давать", de: "geben" },
  { rus: "брать", de: "nehmen" },
  { rus: "говорить", de: "sprechen" },
  { rus: "забывать", de: "vergessen" },
  { rus: "помогать", de: "helfen" },
  { rus: "встречать", de: "treffen" },
  { rus: "бросать, кидать", de: "werfen" },
  { rus: "видеть", de: "sehen" },
  { rus: "читать", de: "lesen" },
  { rus: "бегать, ходить", de: "laufen" },
  { rus: "падать", de: "fallen" },
  { rus: "носить", de: "tragen" },
  { rus: "спать", de: "schlafen" },
  { rus: "мыть, стирать", de: "waschen" },
  { rus: "расти", de: "wachsen" },
  { rus: "ехать", de: "fahren" },
  { rus: "ловить", de: "fangen" },
  { rus: "всегда", de: "Immer" },
  { rus: "иногда", de: "Manchmal" },
  { rus: "сейчас", de: "Jetzt" },
  { rus: "редко", de: "Selten" },
  { rus: "часто", de: "Oft" },
  { rus: "вчера", de: "Gestern" },
  { rus: "сегодня", de: "Heute" },
  { rus: "завтра", de: "Morgen" },
  { rus: "правильно", de: "Richtig" },
  { rus: "неправильно", de: "Falsch" },
];
export const lesson1sentence: IWord[] = [
  { rus: "Ты ешь много", de: "Du isst viel" },
  { rus: "Она ест мало", de: "Sie isst wenig" },
  { rus: "Ты даешь книгу", de: "Du gibst ein Buch" },
  { rus: "Она дает машину", de: "Sie gibt ein Auto" },
  { rus: "Ты берешь машину", de: "Du nimmst ein Auto" },
  { rus: "Он берет книгу", de: "Er nimmt ein Buch" },
  { rus: "Ты встречаешь подругу", de: "Du triffst eine Freundin" },
  { rus: "Он встречает ребенка", de: "Er trifft ein Kind" },
  { rus: "Ты говоришь быстро", de: "Du sprichst schnell" },
  { rus: "Она говорит медленно", de: "Sie spricht langsam" },
  { rus: "Ты забываешь редко", de: "Du vergisst selten" },
  { rus: "Он забывает часто", de: "Er vergisst oft" },
  { rus: "Ты помогаешь сегодня", de: "Du hilfst heute" },
  { rus: "Он помогает завтра", de: "Er hilft morgen" },
  { rus: "Ты говоришь громко", de: "Du sprichst laut" },
  { rus: "Она говорит тихо", de: "Sie spricht leise" },
  { rus: "Ты бросаешь далеко", de: "Du wirfst weit" },
  { rus: "Она бросает близко", de: "Sie wirft nah" },
  { rus: "Ты видишь хорошо", de: "Du siehst gut" },
  { rus: "Она видит плохо", de: "Sie sieht schlecht" },
  { rus: "Ты читаешь правильно", de: "Du liest richtig" },
  { rus: "Она читает неправильно", de: "Sie liest falsch" },
  { rus: "Ты бегаешь медленно", de: "Du läufst langsam" },
  { rus: "Она бегает быстро", de: "Sie läuft schnell" },
  { rus: "Ты падаешь часто", de: "Du fällst oft" },
  { rus: "Она падает редко", de: "Sie fällt selten" },
  { rus: "Ты спишь много", de: "Du schläfst viel" },
  { rus: "Он спит мало", de: "Er schläft wenig" },
  { rus: "Ты растешь быстро", de: "Du wächst schnell" },
  { rus: "Она растет медленно", de: "Sie wächst langsam" },
  { rus: "Ты моешь машину", de: "Du wäschst das Auto" },
  { rus: "Она моет квартиру", de: "Sie wäscht die Wohnung" },
  { rus: "Ты едешь быстро", de: "Du fährst schnell" },
  { rus: "Она едет медленно", de: "Sie fährt langsam" },
  { rus: "Ты ловишь книгу", de: "Du fängst das Buch" },
  { rus: "Она ловит кошку", de: "Sie fängt die Katze" },
  { rus: "Она спит долго", de: "Sie schläft lange" },
  { rus: "Он сейчас спит", de: "Er schläft jetzt" },
  { rus: "Ты ездишь правильно", de: "Du fährst richtig" },
  { rus: "Он ездит неправильно", de: "Er fährt falsch" },
  { rus: "Ты носишь брюки", de: "Du trägst die Hose" },
  { rus: "Она носит платье", de: "Sie trägt das Kleid" },
];
export const roomItems: IWord[] = [
  { rus: "мобильный телефон", de: "Das Handy" },
  { rus: "диван", de: "Das Sofa" },
  { rus: "стул", de: "Der Stuhl" },
  { rus: "ручка", de: "Der Stift" },
  { rus: "картина", de: "Das Bild" },
  { rus: "стена", de: "Die Wand" },
  { rus: "стол", de: "Der Tisch" },
  { rus: "подушка", de: "Das Kissen" },
  { rus: "компьютер", de: "Der Computer" },
  { rus: "окно", de: "Das Fenster" },
  { rus: "дверь", de: "Die Tür" },
  { rus: "телевизор", de: "Der Fernseher" },
  { rus: "книга", de: "Das Buch" },
  { rus: "комод", de: "Die Kommode" },
  { rus: "ковер", de: "Der Teppich" },
  { rus: "лампа", de: "Die Lampe" },
  { rus: "зеркало", de: "Der Spiegel" },
  { rus: "шкаф", de: "Der Schrank" },
  { rus: "часы", de: "Die Uhr" },
  { rus: "кресло", de: "Der Sessel" },
  { rus: "полка", de: "Das Regal" },
  { rus: "пульт", de: "Die Fernbedienung" },
  { rus: "карта", de: "Die Karte" },
  { rus: "сумка", de: "Die Tasche" },
  { rus: "цветок", de: "Die Blume" },
  { rus: "мышь", de: "Die Maus" },
  { rus: "телефон", de: "Das Telefon" },
  { rus: "клавиатура", de: "Die Tastatur" },
  { rus: "чашка", de: "Die Tasse" },
  { rus: "салфетка", de: "Die Serviette" },
  { rus: "штора", de: "Der Vorhang" },
  { rus: "поднос", de: "Das Tablett" },
  { rus: "газета", de: "Die Zeitung" },
  { rus: "ваза", de: "Die Vase" },
  { rus: "горшок", de: "Der Topf" },
  { rus: "микроволновая печь", de: "Die Mikrowelle" },
  { rus: "холодильник", de: "Der Kühlschrank" },
  { rus: "компакт-диск", de: "Die CD" },
  { rus: "DVD-плеер", de: "Der DVD-Player" },
  { rus: "кондиционер", de: "Die Klimaanlage" },
  { rus: "плед", de: "Die Decke" },
  { rus: "детская кроватка", de: "Das Kinderbett" },
  { rus: "полотенце", de: "Das Handtuch" },
  { rus: "занавеска", de: "Die Gardine" },
  { rus: "стиральная машина", de: "Die Waschmaschine" },
  { rus: "крючок", de: "Der Haken" },
  { rus: "зеркало", de: "Der Spiegel" },
  { rus: "вешалка", de: "Der Kleiderbügel" },
];
export const lesson1_1sentence: IWord[] = [
  {
    rus: "В комнате есть стул.",
    de: "In dem Zimmer ist ein Stuhl.",
  },
  {
    rus: "Стул стоит на ковре.",
    de: "Der Stuhl steht auf dem Teppich.",
  },
  {
    rus: "Ковер лежит на полу.",
    de: "Der Teppich liegt auf dem Boden.",
  },
  {
    rus: "На столе стоит ваза.",
    de: "Auf dem Tisch steht eine Vase.",
  },
  {
    rus: "Очки лежат рядом с вазой.",
    de: "Die Brille liegt neben der Vase.",
  },
  {
    rus: "Ковер находится под столом.",
    de: "Der Teppich ist unter dem Tisch.",
  },
  {
    rus: "На столе лежит ручка.",
    de: "Auf dem Tisch liegt ein Stift.",
  },
  {
    rus: "Мобильный телефон находится рядом с очками.",
    de: "Das Handy ist neben der Brille.",
  },
  {
    rus: "Лампа стоит на шкафу.",
    de: "Die Lampe steht auf dem Schrank.",
  },
  {
    rus: "Газета лежит на диване.",
    de: "Die Zeitung liegt auf dem Sofa.",
  },
  {
    rus: "Цветок находится в вазе.",
    de: "Die Blume ist in der Vase.",
  },
  {
    rus: "Книга лежит на полке.",
    de: "Das Buch liegt auf dem Regal.",
  },
  {
    rus: "Зеркало висит на стене.",
    de: "Der Spiegel hängt an der Wand.",
  },
  {
    rus: "Телевизор стоит на телестойке.",
    de: "Der Fernseher steht auf dem TV-Ständer.",
  },
  {
    rus: "Подушка лежит на кровати.",
    de: "Das Kissen liegt auf dem Bett.",
  },
  {
    rus: "Картина висит над диваном.",
    de: "Das Bild hängt über dem Sofa.",
  },
  {
    rus: "Чашка стоит на чашке.",
    de: "Die Tasse steht auf der Tasse.",
  },
  {
    rus: "Обувь стоит перед дверью.",
    de: "Die Schuhe stehen vor der Tür.",
  },
  {
    rus: "Шкаф находится рядом с окном.",
    de: "Der Schrank ist neben dem Fenster.",
  },
  {
    rus: "Гитара стоит в углу.",
    de: "Die Gitarre steht in der Ecke.",
  },
  {
    rus: "Постер висит на двери.",
    de: "Das Poster hängt an der Tür.",
  },
  {
    rus: "Ручка лежит под книгой.",
    de: "Der Stift ist unter dem Buch.",
  },
  {
    rus: "Блузка висит в шкафу.",
    de: "Die Bluse hängt im Schrank.",
  },
  {
    rus: "Чашка стоит на подставке.",
    de: "Die Tasse steht auf dem Untersetzer.",
  },
  {
    rus: "Будильник лежит на ночном столике.",
    de: "Der Wecker liegt auf dem Nachttisch.",
  },
  {
    rus: "Куртка висит на вешалке.",
    de: "Die Jacke hängt an der Garderobe.",
  },
  {
    rus: "Плюшевый мишка лежит на подушке.",
    de: "Das Kuscheltier liegt auf dem Kissen.",
  },
  {
    rus: "Тарелки находятся в шкафу.",
    de: "Die Teller sind im Schrank.",
  },
  {
    rus: "Сумка стоит на стуле.",
    de: "Die Tasche steht auf dem Stuhl.",
  },
  {
    rus: "Игрушки лежат на полу.",
    de: "Das Spielzeug liegt auf dem Boden.",
  },
  {
    rus: "Картина висит на стене.",
    de: "Das Gemälde hängt an der Wand.",
  },
  {
    rus: "Пульт от телевизора лежит на диване.",
    de: "Die Fernbedienung liegt auf dem Sofa.",
  },
  {
    rus: "Чашка стоит на столе.",
    de: "Die Tasse steht auf dem Tisch.",
  },
  {
    rus: "Ключ лежит на комоде.",
    de: "Der Schlüssel liegt auf der Kommode.",
  },
  {
    rus: "Цветок стоит на подоконнике.",
    de: "Die Blume steht auf dem Fensterbrett.",
  },
  {
    rus: "Картина висит над кроватью.",
    de: "Das Bild hängt über dem Bett.",
  },
  {
    rus: "Шапка лежит на шкафу.",
    de: "Die Mütze liegt auf dem Schrank.",
  },
  {
    rus: "Книга лежит под подушкой.",
    de: "Das Buch ist unter dem Kissen.",
  },
  {
    rus: "Ноутбук стоит на столе.",
    de: "Der Laptop steht auf dem Schreibtisch.",
  },
  {
    rus: "Газета лежит на столе.",
    de: "Die Zeitung liegt auf dem Tisch.",
  },
  {
    rus: "Одеяло лежит на диване.",
    de: "Die Decke liegt auf dem Sofa.",
  },
  {
    rus: "Очки стоят на столе.",
    de: "Die Brille liegt auf dem Nachttisch.",
  },
  {
    rus: "Куртка висит на вешалке.",
    de: "Die Jacke hängt am Haken.",
  },
  {
    rus: "Игрушки лежат под стулом.",
    de: "Das Spielzeug liegt unter dem Stuhl.",
  },
  {
    rus: "Картина висит над столом.",
    de: "Das Gemälde hängt über dem Schreibtisch.",
  },
  {
    rus: "Ручка лежит на полке.",
    de: "Der Stift liegt auf dem Regal.",
  },
  {
    rus: "Блузка висит на стене.",
    de: "Die Bluse hängt an der Wand.",
  },
];
export const lesson1_1WordsArr: IWord[] = [
  { rus: "ложка", de: "Der Löffel" },
  { rus: "вилка", de: "Die Gabel" },
  { rus: "нож", de: "Das Messer" },
  { rus: "тарелка", de: "Der Teller" },
  { rus: "чашка", de: "Die Tasse" },
  { rus: "блюдце", de: "Die Untertasse" },
  { rus: "чайник", de: "Die Teekanne" },
  { rus: "чайная ложка", de: "Der Teelöffel" },
  { rus: "сахарница", de: "Der Zuckertopf" },
  { rus: "сольница", de: "Der Salzstreuer" },
  { rus: "перечница", de: "Der Pfefferstreuer" },
  { rus: "бокал", de: "Das Glas" },
  { rus: "столовая ложка", de: "Der Esslöffel" },
  { rus: "винный бокал", de: "Das Weinglas" },
  { rus: "кружка", de: "Der Krug" },
  { rus: "салатник", de: "Die Salatschüssel" },
  { rus: "поднос", de: "Das Tablett" },
  { rus: "доска для нарезки", de: "Das Schneidebrett" },
  { rus: "салфетка", de: "Die Serviette" },
  { rus: "открывашка", de: "Der Flaschenöffner" },
  { rus: "винтовка", de: "Der Korkenzieher" },
  { rus: "скатерть", de: "Die Tischdecke" },
];

export const lesson6sentence: IWord[] = [
  { rus: "Ему можно быстро бегать", de: "Er darf schnell laufen" },
  { rus: "Она умеет красиво петь", de: "Sie kann schön singen" },
  { rus: "Нам можно громко петь", de: "Wir dürfen laut singen" },
  { rus: "Он умеет быстро бегать", de: "Er kann schnell laufen" },
  { rus: "Им можно тихо поиграть", de: "Sie dürfen leise spielen" },
  { rus: "Ему можно спросить", de: "Er darf fragen" },
  { rus: "Мы умеем хорошо танцевать", de: "Wir können gut tanzen" },
  { rus: "Я могу ответить", de: "Ich kann antworten" },
  { rus: "Она может быстро читать", de: "Sie kann schnell lesen" },
  { rus: "Он может много выпить", de: "Er kann viel trinken" },
  { rus: "Отец умеет быстро ездить", de: "Der Vater kann schnell fahren" },
  { rus: "Мама умеет хорошо готовить", de: "Die Mutter kann gut kochen" },
  { rus: "Дедушка может долго спать", de: "Der Opa kann lange schlafen" },
  { rus: "Брат может высоко прыгать", de: "Der Bruder kann hoch springen" },
  { rus: "Он обязан учить немецкий", de: "Er soll Deutsch lernen" },
  { rus: "Она обязана хорошо танцевать", de: "Sie soll gut tanzen" },
  { rus: "Я должен хорошо учиться", de: "Ich muss gut lernen" },
  { rus: "Я должен сегодня играть", de: "Ich muss heute spielen" },
  { rus: "Ты обязан завтра помочь", de: "Du sollst morgen helfen" },
  { rus: "Она должна сегодня написать", de: "Sie muss heute schreiben" },
  { rus: "Вам (ihr) надо покушать", de: "Ihr müsst essen" },
  { rus: "Они обязаны прийти!", de: "Sie sollen kommen!" },
  { rus: "Ты должен помочь", de: "Du musst helfen" },
  { rus: "Мы обязаны работать", de: "Wir sollen arbeiten" },
  { rus: "Ты обязан учить немецкий!", de: "Du sollst Deutsch lernen" },
  { rus: "Она обязана помочь", de: "Sie soll helfen" },
  { rus: "Тебе надо учить немецкий", de: "Du musst Deutsch lernen" },
  { rus: "Я люблю пиццу", de: "Ich mag Pizza" },
  { rus: "Я хочу купить пиццу", de: "Ich will Pizza kaufen" },
  { rus: "Я хотел бы заказать пиццу", de: "Ich möchte Pizza bestellen" },
  { rus: "Она любит английский", de: "Sie mag Englisch" },
  { rus: "Он хотел бы учить немецкий", de: "Er möchte Deutsch lernen" },
  { rus: "Она хотела бы танцевать", de: "Sie möchte tanzen" },
  {
    rus: "Мы хотим сегодня купить велосипед",
    de: "Wir wollen heute ein Fahrrad kaufen",
  },
  { rus: "Он хочет есть", de: "Er will essen" },
  { rus: "Ты любишь футбол", de: "Du magst Fußball" },
  { rus: "Я хочу пить", de: "Ich will trinken" },
  { rus: "Мы хотим купить машину", de: "Wir wollen ein Auto kaufen" },
  { rus: "Мы хотели бы выпить колы", de: "Wir möchten Cola trinken" },
  { rus: "Они хотят помочь", de: "Sie wollen helfen" },
  { rus: "Я люблю немецкий", de: "Ich mag Deutsch" },
  { rus: "Вы (ihr) любите танцевать", de: "Ihr mögt Musik" },
  { rus: "Они хотят купить машину", de: "Sie wollen ein Auto kaufen" },
];
export const lesson7WordArr: IWord[] = [
  { rus: "пиджак", de: "Der Anzug" },
  { rus: "свитер", de: "Der Pullover" },
  { rus: "шляпа", de: "Der Hut" },
  { rus: "юбка", de: "Der Rock" },
  { rus: "пальто", de: "Der Mantel" },
  { rus: "шарф", de: "Der Schal" },
  { rus: "рубашка", de: "Das Hemd" },
  { rus: "платье", de: "Das Kleid" },
  { rus: "футболка", de: "Das T-shirt (англ)" },
  { rus: "блузка", de: "Die Bluse" },
  { rus: "брюки", de: "Die Hose" },
  { rus: "куртка", de: "Die Jacke" },
  { rus: "одежда", de: "Die Kleidung" },
  { rus: "шапка", de: "Die Mütze" },
  { rus: "колготки", de: "Die Strumpfhose" },
  { rus: "джинсы", de: "Die Jeans" },
  { rus: "туфли", de: "Die Schuhe" },
  { rus: "перчатки", de: "Die Handschuhe" },
  { rus: "носки", de: "Die Socken" },
  { rus: "Красный", de: "Rot" },
  { rus: "Зеленый", de: "Grün" },
  { rus: "Синий", de: "Blau" },
  { rus: "Желтый", de: "Gelb" },
  { rus: "Розовый", de: "Rosa" },
  { rus: "Оранжевый", de: "Orange" },
  { rus: "Черный", de: "Schwarz" },
  { rus: "Белый", de: "Weiß" },
  { rus: "Коричневый", de: "Braun" },
  { rus: "Серый", de: "Grau" },
];
export const lesson7Sentence: IWord[] = [
  { rus: "Это мой костюм", de: "Das ist mein Anzug" },
  { rus: "Это твой свитер", de: "Das ist dein Pullover" },
  { rus: "Это его шляпа", de: "Das ist sein Hut" },
  { rus: "Это ее юбка", de: "Das ist ihr Rock" },
  { rus: "Это наше пальто", de: "Das ist unser Mantel" },
  { rus: "Это ваш шарф", de: "Das ist euer Schal" },
  { rus: "Это их рубашка", de: "Das ist ihr Hemd" },
  { rus: "Это мое платье", de: "Das ist mein Kleid" },
  { rus: "Это твоя футболка", de: "Das ist dein T-Shirt" },
  { rus: "Это ее блузка", de: "Das ist ihre Bluse" },
  { rus: "Это его штаны", de: "Das sind seine Hosen" },
  { rus: "Это наша куртка", de: "Das ist unsere Jacke" },
  { rus: "Это ваша одежда", de: "Das ist eure Kleidung" },
  { rus: "Это их шапка", de: "Das ist ihr Hut" },
  { rus: "Это ее колготки", de: "Das sind ihre Strumpfhosen" },
  { rus: "Это мои джинсы (Pl)", de: "Das sind meine Jeans" },
  { rus: "Это мои ботинки (Pl)", de: "Das sind meine Schuhe" },
  { rus: "Это твои носки (Pl)", de: "Das sind deine Socken" },
  { rus: "Мои носки старые", de: "Meine Socken sind alt" },
  { rus: "Наша шапка красивая", de: "Unsere Mütze ist schön" },
  { rus: "Ее колготки дешевые", de: "Ihre Strumpfhosen sind billig" },
  { rus: "Твои ботинки новые (Pl)", de: "Deine Schuhe sind neu" },
  { rus: "Его джинсы дорогие (Pl)", de: "Seine Jeans sind teuer" },
  { rus: "Ваша одежда грязная", de: "Ihre Kleidung ist schmutzig" },
  { rus: "Их куртка чистая", de: "Ihre Jacke ist sauber" },
  { rus: "Мои штаны новые", de: "Meine Hosen sind neu" },
  { rus: "Твоя блузка старая", de: "Deine Bluse ist alt" },
  { rus: "Его футболка дешевая", de: "Sein T-Shirt ist billig" },
  { rus: "Ее платье дорогое", de: "Ihr Kleid ist teuer" },
  { rus: "Моя рубашка белая", de: "Mein Hemd ist weiß" },
  { rus: "Твой шарф черный", de: "Dein Schal ist schwarz" },
  { rus: "Его пальто серое", de: "Sein Mantel ist grau" },
  { rus: "Ее юбка коричневая", de: "Ihr Rock ist braun" },
  { rus: "Его шляпа зеленая", de: "Sein Hut ist grün" },
  { rus: "Мой свитер красный", de: "Mein Pullover ist rot" },
  { rus: "Его костюм зеленый", de: "Sein Anzug ist grün" },
  { rus: "Их одежда оранжевая", de: "Ihre Kleidung ist orange" },
  { rus: "Ее джинсы голубые (Pl)", de: "Ihre Jeans sind blau" },
  {
    rus: "У моего папы есть машина. Он продает свою машину.",
    de: "Mein Vater hat ein Auto. Er verkauft sein Auto.",
  },
  {
    rus: "У моего друга есть велосипед. Он продает свой велосипед.",
    de: "Mein Freund hat ein Fahrrad. Er verkauft sein Fahrrad.",
  },
  {
    rus: "У меня есть дом. Я продаю свой дом.",
    de: "Ich habe ein Haus. Ich verkaufe mein Haus.",
  },
  {
    rus: "У твоей сестры есть кошка. Она продает свою кошку.",
    de: "Deine Schwester hat eine Katze. Sie verkauft ihre Katze.",
  },
  {
    rus: "У тебя есть сестра. Ты любишь свою сестру.",
    de: "Du hast eine Schwester. Du liebst deine Schwester.",
  },
  {
    rus: "У его брата есть дом. Он продает свой дом.",
    de: "Sein Bruder hat ein Haus. Er verkauft sein Haus.",
  },
  {
    rus: "У ее мамы есть машина. Она продает свою машину.",
    de: "Ihre Mutter hat ein Auto. Sie verkauft ihr Auto.",
  },
  {
    rus: "У нас есть квартира. Мы продаем свою квартиру.",
    de: "Wir haben eine Wohnung. Wir verkaufen unsere Wohnung.",
  },
  {
    rus: "У вас есть корабль. Вы продаете свой корабль.",
    de: "Ihr habt ein Schiff. Ihr verkauft euer Schiff.",
  },
  {
    rus: "У наших друзей есть квартира. Они продают свою квартиру.",
    de: "Unsere Freunde haben eine Wohnung. Sie verkaufen ihre Wohnung.",
  },
];

export const lesson8_1Sentence: IWord[] = [
  { rus: "Ты сильный?", de: "Bist du stark?" },
  { rus: "Она молодая?", de: "Ist sie jung?" },
  { rus: "Он сильный?", de: "Ist er stark?" },
  { rus: "Твой папа умный?", de: "Ist dein Vater klug?" },
  { rus: "Ее мама красивая?", de: "Ist ihre Mutter schön?" },
  { rus: "У вас (ihr) есть квартира?", de: "Habt ihr eine Wohnung?" },
  { rus: "У тебя есть машина?", de: "Hast du ein Auto?" },
  { rus: "У твоего папы есть сестра?", de: "Hat dein Vater eine Schwester?" },
  { rus: "У его сестры есть кошка?", de: "Hat seine Schwester eine Katze?" },
  { rus: "Ты спишь?", de: "Schläfst du?" },
  { rus: "Он ездит быстро?", de: "Fährt er schnell?" },
  { rus: "Ты покупаешь мою машину?", de: "Kaufst du mein Auto?" },
  { rus: "Она поет хорошо?", de: "Singt sie gut?" },
  { rus: "Ты едешь?", de: "Fährst du?" },
  { rus: "Вы (Sie) пьете чай?", de: "Trinken Sie Tee?" },
  { rus: "Ты читаешь?", de: "Liest du?" },
  { rus: "Ты хочешь поиграть?", de: "Willst du spielen?" },
  { rus: "Ей можно здесь бегать?", de: "Darf sie hier laufen?" },
  { rus: "Вы (Ihr) можете помочь?", de: "Könnt ihr helfen?" },
  { rus: "Ты хочешь тоже заказать?", de: "Willst du auch bestellen?" },
  { rus: "Должен ли я помочь?", de: "Soll ich helfen?" },
  { rus: "Ты должен учить немецкий?", de: "Musst du Deutsch lernen?" },
];
export const lesson8_2Sentence: IWord[] = [
  { rus: "Почему ты такой сильный?", de: "Warum bist du so stark?" },
  { rus: "Почему он такой слабый?", de: "Warum ist er so schwach?" },
  { rus: "Сколько у тебя твоя машина?", de: "Wie lange hast du dein Auto?" },
  { rus: "Когда ты спишь?", de: "Wann schläfst du?" },
  { rus: "Где ты покупаешь машину?", de: "Wo kaufst du das Auto?" },
  { rus: "Где ты едешь?", de: "Wo fährst du?" },
  { rus: "Где ты хочешь играть?", de: "Wo willst du spielen?" },
  { rus: "Кому можно здесь бегать?", de: "Wer darf hier laufen?" },
  { rus: "Когда вы (ihr) можете помочь?", de: "Wann könnt ihr helfen?" },
  { rus: "Что ты хочешь заказать?", de: "Was möchtest du bestellen?" },
  { rus: "Кому я должен помочь?", de: "Wem soll ich helfen?" },
  {
    rus: "Почему я должен учить немецкий?",
    de: "Warum soll ich Deutsch lernen?",
  },
  { rus: "Кто хочет танцевать?", de: "Wer will tanzen?" },
  { rus: "Что ты хочешь заказать?", de: "Was möchtest du bestellen?" },
  { rus: "Кому ты даришь машину?", de: "Wem schenkst du das Auto?" },
  { rus: "Где он живет?", de: "Wo wohnt er?" },
  { rus: "Где она играет?", de: "Wo spielt sie?" },
  { rus: "Как долго он учит немецкий?", de: "Wie lange lernt er Deutsch?" },
  { rus: "Как тебя зовут?", de: "Wie heißt du?" },
  { rus: "Где ты живешь?", de: "Wo wohnst du?" },
  { rus: "Что ты делаешь?", de: "Was machst du?" },
  { rus: "Кому ты помогаешь?", de: "Wem hilfst du?" },
  { rus: "Кого ты любишь?", de: "Wen liebst du?" },
  { rus: "Откуда ты едешь?", de: "Woher fährst du?" },
  { rus: "Куда ты идешь?", de: "Wohin gehst du?" },
  {
    rus: "Сколько ты уже учишь немецкий?",
    de: "Wie lange lernst du schon Deutsch.",
  },
  { rus: "Сколько ты спишь?", de: "Wie lange schläfst du?" },
  { rus: "Когда ты приедешь?", de: "Wann kommst du?" },
  { rus: "Как его зовут?", de: "Wie heißt er?" },
  { rus: "Где он живет?", de: "Wo wohnt er?" },
  { rus: "Что он делает?", de: "Was macht er?" },
  { rus: "Кому он помогает?", de: "Wem hilft er?" },
  { rus: "Кого он любит?", de: "Wen liebt er?" },
  { rus: "Откуда он едет?", de: "Woher fährt er?" },
  { rus: "Куда он идет?", de: "Wohin geht er?" },
  {
    rus: "Сколько он уже учит немецкий?",
    de: "Wie lange lernt er schon Deutsch.",
  },
  { rus: "Сколько он спит?", de: "Wie lange schläft er?" },
  { rus: "Когда он приедет?", de: "Wann kommt er?" },
];
export const a1Words: IWord[] = [
  { rus: "der Mann", de: "мужчина" },
  { rus: "die Frau", de: "женщина" },
  { rus: "das Kind", de: "ребенок" },
  { rus: "die Familie", de: "семья" },
  { rus: "der Freund / die Freundin", de: "друг / подруга" },
  { rus: "das Haus", de: "дом" },
  { rus: "die Wohnung", de: "квартира" },
  { rus: "das Auto", de: "автомобиль" },
  { rus: "die Straße", de: "улица" },
  { rus: "die Stadt", de: "город" },
  { rus: "das Land", de: "страна" },
  { rus: "die Arbeit", de: "работа" },
  { rus: "die Schule", de: "школа" },
  { rus: "das Buch", de: "книга" },
  { rus: "die Zeit", de: "время" },
  { rus: "heute", de: "сегодня" },
  { rus: "morgen", de: "завтра" },
  { rus: "gestern", de: "вчера" },
  { rus: "groß", de: "большой" },
  { rus: "klein", de: "маленький" },
  { rus: "schön", de: "красивый" },
  { rus: "hässlich", de: "уродливый" },
  { rus: "alt", de: "старый" },
  { rus: "jung", de: "молодой" },
  { rus: "gut", de: "хороший" },
  { rus: "schlecht", de: "плохой" },
  { rus: "richtig", de: "правильный" },
  { rus: "falsch", de: "неправильный" },
  { rus: "einfach", de: "простой" },
  { rus: "schwer", de: "сложный" },
  { rus: "neu", de: "новый" },
  { rus: "alt", de: "старый" },
  { rus: "billig", de: "дешевый" },
  { rus: "teuer", de: "дорогой" },
  { rus: "langsam", de: "медленный" },
  { rus: "schnell", de: "быстрый" },
  { rus: "glücklich", de: "счастливый" },
  { rus: "traurig", de: "грустный" },
  { rus: "kalt", de: "холодный" },
  { rus: "heiß", de: "горячий" },
  { rus: "der Tisch", de: "стол" },
  { rus: "der Stuhl", de: "стул" },
  { rus: "das Bett", de: "кровать" },
  { rus: "das Bad", de: "ванная комната" },
  { rus: "das Zimmer", de: "комната" },
  { rus: "das Essen", de: "еда" },
  { rus: "das Frühstück", de: "завтрак" },
  { rus: "das Mittagessen", de: "обед" },
  { rus: "das Abendessen", de: "ужин" },
  { rus: "trinken", de: "пить" },
  { rus: "essen", de: "есть" },
  { rus: "schlafen", de: "спать" },
  { rus: "arbeiten", de: "работать" },
  { rus: "lernen", de: "учиться" },
  { rus: "lesen", de: "читать" },
  { rus: "schreiben", de: "писать" },
  { rus: "hören", de: "слушать" },
  { rus: "sehen", de: "видеть" },
  { rus: "sprechen", de: "говорить" },
  { rus: "verstehen", de: "понимать" },
  { rus: "kaufen", de: "покупать" },
  { rus: "verkaufen", de: "продавать" },
  { rus: "helfen", de: "помогать" },
  { rus: "fragen", de: "спрашивать" },
  { rus: "antworten", de: "отвечать" },
  { rus: "kommen", de: "приходить" },
  { rus: "gehen", de: "идти" },
  { rus: "stehen", de: "стоять" },
  { rus: "sitzen", de: "сидеть" },
  { rus: "lieben", de: "любить" },
  { rus: "der Lehrer / die Lehrerin", de: "учитель / учительница" },
  { rus: "der Schüler / die Schülerin", de: "ученик / ученица" },
  { rus: "die Universität", de: "университет" },
  { rus: "das Handy", de: "мобильный телефон" },
  { rus: "das Geld", de: "деньги" },
  { rus: "die Uhr", de: "часы" },
  { rus: "die Farbe", de: "цвет" },
  { rus: "der Monat", de: "месяц" },
  { rus: "die Woche", de: "неделя" },
  { rus: "das Jahr", de: "год" },
  { rus: "der Tag", de: "день" },
  { rus: "die Nacht", de: "ночь" },
  { rus: "die Arbeit", de: "работа" },
  { rus: "der Urlaub", de: "отпуск" },
  { rus: "der Flughafen", de: "аэропорт" },
  { rus: "das Flugzeug", de: "самолет" },
  { rus: "die Reise", de: "путешествие" },
  { rus: "die Karte", de: "карта" },
  { rus: "der Pass", de: "паспорт" },
  { rus: "die Post", de: "почта" },
  { rus: "die E-Mail", de: "электронная почта" },
  { rus: "das Foto", de: "фотография" },
  { rus: "das Wetter", de: "погода" },
  { rus: "die Sonne", de: "солнце" },
  { rus: "der Regen", de: "дождь" },
  { rus: "der Schnee", de: "снег" },
  { rus: "die Wolke", de: "облако" },
  { rus: "der Wind", de: "ветер" },
  { rus: "der Frühling", de: "весна" },
  { rus: "der Sommer", de: "лето" },
  { rus: "der Herbst", de: "осень" },
  { rus: "der Winter", de: "зима" },
  { rus: "die Jahreszeit", de: "время года" },
  { rus: "der Markt", de: "рынок" },
  { rus: "das Geschäft", de: "магазин" },
  { rus: "das Kaufhaus", de: "универмаг" },
  { rus: "die Apotheke", de: "аптека" },
  { rus: "das Krankenhaus", de: "больница" },
  { rus: "der Arzt / die Ärztin", de: "врач" },
  { rus: "die Krankheit", de: "болезнь" },
  { rus: "die Gesundheit", de: "здоровье" },
  { rus: "das Restaurant", de: "ресторан" },
  { rus: "das Café", de: "кафе" },
  { rus: "die Speisekarte", de: "меню" },
  { rus: "das Frühstück", de: "завтрак" },
  { rus: "das Mittagessen", de: "обед" },
  { rus: "das Abendessen", de: "ужин" },
  { rus: "die Suppe", de: "суп" },
  { rus: "das Fleisch", de: "мясо" },
  { rus: "der Fisch", de: "рыба" },
  { rus: "das Gemüse", de: "овощи" },
  { rus: "die Frucht", de: "фрукт" },
  { rus: "das Getränk", de: "напиток" },
  { rus: "der Tee", de: "чай" },
  { rus: "der Kaffee", de: "кофе" },
  { rus: "das Wasser", de: "вода" },
  { rus: "die Milch", de: "молоко" },
  { rus: "das Brot", de: "хлеб" },
  { rus: "die Butter", de: "масло" },
  { rus: "der Käse", de: "сыр" },
  { rus: "das Ei", de: "яйцо" },
  { rus: "die Marmelade", de: "варенье" },
  { rus: "das Obst", de: "фрукты" },
  { rus: "die Erdbeere", de: "клубника" },
  { rus: "die Apfel", de: "яблоко" },
  { rus: "die Banane", de: "банан" },
  { rus: "die Orange", de: "апельсин" },
  { rus: "die Zitrone", de: "лимон" },
  { rus: "die Tomate", de: "помидор" },
  { rus: "die Gurke", de: "огурец" },
  { rus: "die Kartoffel", de: "картошка" },
  { rus: "das Eis", de: "мороженое" },
  { rus: "die Schokolade", de: "шоколад" },
  { rus: "das Dessert", de: "десерт" },
  { rus: "die Tasse", de: "чашка" },
  { rus: "der Teller", de: "тарелка" },
  { rus: "das Messer", de: "нож" },
  { rus: "die Gabel", de: "вилка" },
  { rus: "der Löffel", de: "ложка" },
  { rus: "die Serviette", de: "салфетка" },
  { rus: "die Küche", de: "кухня" },
  { rus: "das Schlafzimmer", de: "спальня" },
  { rus: "das Wohnzimmer", de: "гостиная" },
  { rus: "das Badezimmer", de: "ванная комната" },
  { rus: "das WC", de: "туалет" },
  { rus: "der Balkon", de: "балкон" },
  { rus: "die Treppe", de: "лестница" },
  { rus: "die Tür", de: "дверь" },
  { rus: "das Fenster", de: "окно" },
  { rus: "das Licht", de: "свет" },
  { rus: "die Blume", de: "цветок" },
  { rus: "der Baum", de: "дерево" },
  { rus: "die Pflanze", de: "растение" },
  { rus: "der Garten", de: "сад" },
  { rus: "die Natur", de: "природа" },
  { rus: "die Tier", de: "животное" },
  { rus: "der Hund", de: "собака" },
  { rus: "die Katze", de: "кошка" },
  { rus: "der Vogel", de: "птица" },
  { rus: "das Insekt", de: "насекомое" },
  { rus: "der Fisch", de: "рыба" },
  { rus: "das Haustier", de: "домашнее животное" },
  { rus: "die Liebe", de: "любовь" },
  { rus: "die Freundschaft", de: "дружба" },
  { rus: "die Hochzeit", de: "свадьба" },
  { rus: "der Geburtstag", de: "день рождения" },
  { rus: "das Geschenk", de: "подарок" },
  { rus: "die Party", de: "вечеринка" },
  { rus: "das Lied", de: "песня" },
  { rus: "die Musik", de: "музыка" },
  { rus: "das Instrument", de: "инструмент" },
  { rus: "die Gitarre", de: "гитара" },
  { rus: "das Klavier", de: "фортепиано" },
  { rus: "die Malerei", de: "живопись" },
  { rus: "die Skulptur", de: "скульптура" },
  { rus: "das Theater", de: "театр" },
  { rus: "der Film", de: "фильм" },
  { rus: "das Kino", de: "кинотеатр" },
  { rus: "die Kunst", de: "искусство" },
  { rus: "das Foto", de: "фотография" },
  { rus: "die Kamera", de: "камера" },
  { rus: "die Rechnung", de: "счет" },
  { rus: "das Geld", de: "деньги" },
  { rus: "die Bank", de: "банк" },
  { rus: "der Kredit", de: "кредит" },
  { rus: "die Karte", de: "карта" },
  { rus: "das Ticket", de: "билет" },
  { rus: "die Reservierung", de: "бронирование" },
  { rus: "das Hotel", de: "отель" },
  { rus: "das Zimmer", de: "номер" },
  { rus: "die Rezeption", de: "стойка регистрации" },
  { rus: "der Schlüssel", de: "ключ" },
  { rus: "die Dusche", de: "душ" },
  { rus: "das Handtuch", de: "полотенце" },
  { rus: "der Strand", de: "пляж" },
  { rus: "das Meer", de: "море" },
  { rus: "die Sonne", de: "солнце" },
  { rus: "der Sand", de: "песок" },
  { rus: "die Welle", de: "волна" },
  { rus: "das Boot", de: "лодка" },
  { rus: "das Schwimmbad", de: "бассейн" },
  { rus: "die Sonnenbrille", de: "солнечные очки" },
  { rus: "die Sonnencreme", de: "солнцезащитный крем" },
  { rus: "der Ausflug", de: "экскурсия" },
  { rus: "die Sehenswürdigkeit", de: "достопримечательность" },
  { rus: "der Turm", de: "башня" },
  { rus: "das Schloss", de: "замок" },
  { rus: "die Brücke", de: "мост" },
  { rus: "die Kirche", de: "церковь" },
  { rus: "das Museum", de: "музей" },
  { rus: "der Park", de: "парк" },
  { rus: "der Markt", de: "рынок" },
  { rus: "der Zoo", de: "зоопарк" },
  { rus: "die Bibliothek", de: "библиотека" },
  { rus: "die Schule", de: "школа" },
  { rus: "das Klassenzimmer", de: "класс" },
  { rus: "der Lehrer", de: "учитель" },
  { rus: "die Schülerin", de: "ученица" },
  { rus: "das Fach", de: "предмет" },
  { rus: "das Buch", de: "книга" },
  { rus: "die Hausaufgaben", de: "домашние задания" },
  { rus: "der Test", de: "тест" },
  { rus: "die Note", de: "отметка" },
  { rus: "das Diplom", de: "диплом" },
  { rus: "der Abschluss", de: "окончание" },
  { rus: "die Universität", de: "университет" },
  { rus: "das Studium", de: "учеба" },
  { rus: "die Vorlesung", de: "лекция" },
  { rus: "die Prüfung", de: "экзамен" },
  { rus: "die Pause", de: "перерыв" },
  { rus: "der Arbeitsplatz", de: "рабочее место" },
  { rus: "der Kollege / die Kollegin", de: "коллега / коллега" },
  { rus: "die Besprechung", de: "совещание" },
  { rus: "das Projekt", de: "проект" },
  { rus: "die Aufgabe", de: "задача" },
  { rus: "die Karriere", de: "карьера" },
  { rus: "der Chef / die Chefin", de: "начальник / начальница" },
  { rus: "die Teamarbeit", de: "командная работа" },
  { rus: "der Erfolg", de: "успех" },
  { rus: "die Herausforderung", de: "вызов" },
  { rus: "die Bewerbung", de: "заявление, резюме" },
  { rus: "das Vorstellungsgespräch", de: "собеседование" },
  { rus: "die Einstellung", de: "найм" },
  { rus: "die Kündigung", de: "увольнение" },
  { rus: "die Rente", de: "пенсия" },
  { rus: "die Steuer", de: "налог" },
  { rus: "das Finanzamt", de: "налоговая инспекция" },
  { rus: "die Versicherung", de: "страховка" },
  { rus: "der Vertrag", de: "контракт" },
  { rus: "die Unterschrift", de: "подпись" },
  { rus: "die Rechnung", de: "счет" },
  { rus: "der Kunde / die Kundin", de: "клиент / клиентка" },
  { rus: "die Dienstleistung", de: "услуга" },
  { rus: "die Bestellung", de: "заказ" },
  { rus: "die Lieferung", de: "доставка" },
  { rus: "der Laden", de: "магазин" },
  { rus: "das Geschäft", de: "бизнес" },
  { rus: "die Ware", de: "товар" },
  { rus: "die Qualität", de: "качество" },
  { rus: "die Marke", de: "бренд" },
  { rus: "das Produkt", de: "продукт" },
  { rus: "die Werbung", de: "реклама" },
  { rus: "das Angebot", de: "предложение" },
  { rus: "die Nachfrage", de: "спрос" },
  { rus: "der Markt", de: "рынок" },
  { rus: "die Konkurrenz", de: "конкуренция" },
  { rus: "das Risiko", de: "риск" },
  { rus: "die Investition", de: "инвестиция" },
  { rus: "die Wirtschaft", de: "экономика" },
  { rus: "die Inflation", de: "инфляция" },
  { rus: "die Bank", de: "банк" },
  { rus: "das Konto", de: "счет" },
  { rus: "die Kreditkarte", de: "кредитная карта" },
  { rus: "der Zins", de: "процент" },
  { rus: "der Kredit", de: "кредит" },
  { rus: "die Schulden", de: "долги" },
  { rus: "die Sparkasse", de: "сберегательная касса" },
  { rus: "die Börse", de: "биржа" },
  { rus: "der Handel", de: "торговля" },
  { rus: "die Krise", de: "кризис" },
  { rus: "das Budget", de: "бюджет" },
  { rus: "der Gewinn", de: "прибыль" },
  { rus: "der Verlust", de: "убыток" },
  { rus: "die Bilanz", de: "баланс" },
  { rus: "die Messe", de: "ярмарка, выставка" },
  { rus: "das Handwerk", de: "ремесло" },
  { rus: "die Dienstleistungsbranche", de: "сфера услуг" },
  { rus: "die Landwirtschaft", de: "сельское хозяйство" },
  {
    rus: "der Handwerker / die Handwerkerin",
    de: "ремесленник / ремесленница",
  },
  { rus: "die Landwirtin", de: "фермерша" },
  { rus: "die Forschung", de: "исследование" },
  { rus: "das Labor", de: "лаборатория" },
  { rus: "der Wissenschaftler / die Wissenschaftlerin", de: "ученый / ученая" },
  { rus: "die Entdeckung", de: "открытие" },
  { rus: "die Innovation", de: "инновация" },
  { rus: "die Technologie", de: "технология" },
  { rus: "der Computer", de: "компьютер" },
  { rus: "das Internet", de: "интернет" },
  { rus: "die Software", de: "программное обеспечение" },
  { rus: "der Code", de: "код" },
  { rus: "die Programmiersprache", de: "язык программирования" },
  { rus: "der Algorithmus", de: "алгоритм" },
  { rus: "die Daten", de: "данные" },
  { rus: "die Cloud", de: "облачное хранилище" },
  { rus: "das Smartphone", de: "смартфон" },
  { rus: "die App", de: "приложение" },
  { rus: "die sozialen Medien", de: "социальные сети" },
  {
    rus: "der Benutzer / die Benutzerin",
    de: "пользователь / пользовательница",
  },
  { rus: "das Passwort", de: "пароль" },
  { rus: "die Sicherheit", de: "безопасность" },
  { rus: "die Umwelt", de: "окружающая среда" },
  { rus: "der Umweltschutz", de: "охрана окружающей среды" },
  { rus: "die Erde", de: "Земля (планета)" },
  { rus: "die Luft", de: "воздух" },
  { rus: "das Wasser", de: "вода" },
  { rus: "der Wald", de: "лес" },
  { rus: "die Pflanze", de: "растение" },
  { rus: "das Tier", de: "животное" },
  { rus: "die Art", de: "вид" },
  { rus: "die Bedrohung", de: "угроза" },
  { rus: "die Ressource", de: "ресурс" },
  { rus: "das Recycling", de: "переработка" },
  { rus: "der Klimawandel", de: "изменение климата" },
  { rus: "die Energie", de: "энергия" },
  { rus: "die Sonnenenergie", de: "солнечная энергия" },
  { rus: "die Windenergie", de: "ветровая энергия" },
  { rus: "die Atomenergie", de: "атомная энергия" },
  { rus: "das Elektroauto", de: "электромобиль" },
  { rus: "der Fahrradweg", de: "велосипедная дорожка" },
  { rus: "die Fußgängerzone", de: "пешеходная зона" },
  { rus: "der Verkehr", de: "движение" },
  { rus: "das Auto", de: "автомобиль" },
  { rus: "der Bus", de: "автобус" },
  { rus: "die Straßenbahn", de: "трамвай" },
  { rus: "die U-Bahn", de: "метро" },
  { rus: "das Flugzeug", de: "самолет" },
  { rus: "der Zug", de: "поезд" },
  { rus: "das Schiff", de: "корабль" },
  { rus: "die Haltestelle", de: "остановка" },
  { rus: "der Fahrplan", de: "расписание" },
  { rus: "die Fahrkarte", de: "билет" },
  { rus: "der Flughafen", de: "аэропорт" },
  { rus: "der Bahnhof", de: "вокзал" },
  { rus: "die Reise", de: "путешествие" },
  { rus: "die Unterkunft", de: "размещение" },
  { rus: "die Pension", de: "пансион" },
  { rus: "die Jugendherberge", de: "молодежная гостиница" },
  { rus: "die Ferienwohnung", de: "квартира на время отпуска" },
  { rus: "die Campingplatz", de: "кемпинг" },
  { rus: "die Sehenswürdigkeit", de: "достопримечательность" },
  { rus: "das Denkmal", de: "памятник" },
  { rus: "die Brücke", de: "мост" },
  { rus: "der Park", de: "парк" },
  { rus: "der Zoo", de: "зоопарк" },
  { rus: "das Museum", de: "музей" },
  { rus: "die Galerie", de: "галерея" },
  { rus: "die Ausstellung", de: "выставка" },
  { rus: "das Konzert", de: "концерт" },
  { rus: "das Theater", de: "театр" },
  { rus: "der Film", de: "фильм" },
  { rus: "die Musik", de: "музыка" },
  { rus: "das Lied", de: "песня" },
  { rus: "der Sänger / die Sängerin", de: "певец / певица" },
  { rus: "das Instrument", de: "инструмент" },
  { rus: "die Gitarre", de: "гитара" },
  { rus: "das Klavier", de: "фортепиано" },
  { rus: "das Schlagzeug", de: "ударные" },
  { rus: "die Stimme", de: "голос" },
  { rus: "der Rhythmus", de: "ритм" },
  { rus: "der Text", de: "текст" },
  { rus: "die Melodie", de: "мелодия" },
  { rus: "das Konzert", de: "концерт" },
  { rus: "die Party", de: "вечеринка" },
  { rus: "die Veranstaltung", de: "мероприятие" },
  { rus: "die Einladung", de: "приглашение" },
  { rus: "der Gast", de: "гость" },
  { rus: "das Geschenk", de: "подарок" },
  { rus: "der Geburtstag", de: "день рождения" },
  { rus: "das Jubiläum", de: "юбилей" },
  { rus: "die Feier", de: "праздник" },
  { rus: "die Dekoration", de: "украшение" },
  { rus: "die Ballons", de: "воздушные шары" },
  { rus: "die Kerzen", de: "свечи" },
  { rus: "die Torte", de: "торт" },
  { rus: "der Champagner", de: "шампанское" },
  { rus: "das Feuerwerk", de: "фейерверк" },
  { rus: "der Karneval", de: "карнавал" },
  { rus: "die Kostümparty", de: "вечеринка в костюмах" },
  { rus: "die Maske", de: "маска" },
  { rus: "die Parade", de: "парад" },
  { rus: "das Kostüm", de: "костюм" },
  { rus: "das Make-up", de: "макияж" },
  { rus: "die Perücke", de: "парик" },
  { rus: "die Tanzfläche", de: "танцпол" },
  { rus: "der DJ", de: "диджей" },
  { rus: "die Disco", de: "дискотека" },
  { rus: "die Stimmung", de: "настроение" },
  { rus: "die Emotion", de: "эмоция" },
  { rus: "das Glück", de: "счастье" },
  { rus: "die Liebe", de: "любовь" },
  { rus: "die Freundschaft", de: "дружба" },
  { rus: "die Trauer", de: "горе" },
  { rus: "die Wut", de: "злость" },
  { rus: "die Überraschung", de: "сюрприз" },
  { rus: "die Freude", de: "радость" },
  { rus: "die Spannung", de: "напряжение" },
  { rus: "die Entspannung", de: "расслабление" },
  { rus: "die Ruhe", de: "покой" },
  { rus: "die Ferien", de: "каникулы" },
  { rus: "der Urlaub", de: "отпуск" },
  { rus: "die Reise", de: "путешествие" },
  { rus: "der Strand", de: "пляж" },
  { rus: "die Sonne", de: "солнце" },
  { rus: "das Meer", de: "море" },
  { rus: "der Berg", de: "гора" },
  { rus: "der See", de: "озеро" },
  { rus: "der Fluss", de: "река" },
  { rus: "der Wald", de: "лес" },
  { rus: "die Natur", de: "природа" },
  { rus: "die Tierwelt", de: "мир животных" },
  { rus: "der Nationalpark", de: "национальный парк" },
  { rus: "das Abenteuer", de: "приключение" },
  { rus: "die Erholung", de: "отдых" },
  { rus: "die Aktivität", de: "активность" },
  { rus: "die Fitness", de: "фитнес" },
  { rus: "das Training", de: "тренировка" },
  { rus: "der Sport", de: "спорт" },
  { rus: "das Spiel", de: "игра" },
  { rus: "der Wettkampf", de: "соревнование" },
  { rus: "der Sieg", de: "победа" },
  { rus: "die Nahrung", de: "пища" },
  { rus: "das Essen", de: "еда" },
  { rus: "der Hunger", de: "голод" },
  { rus: "der Durst", de: "жажда" },
  { rus: "das Frühstück", de: "завтрак" },
  { rus: "das Mittagessen", de: "обед" },
  { rus: "das Abendessen", de: "ужин" },
  { rus: "die Mahlzeit", de: "прием пищи" },
  { rus: "der Teller", de: "тарелка" },
  { rus: "die Gabel", de: "вилка" },
  { rus: "das Messer", de: "нож" },
  { rus: "der Löffel", de: "ложка" },
  { rus: "die Küche", de: "кухня" },
  { rus: "der Koch / die Köchin", de: "повар / повариха" },
  { rus: "das Restaurant", de: "ресторан" },
  { rus: "die Speisekarte", de: "меню" },
  { rus: "die Suppe", de: "суп" },
  { rus: "der Salat", de: "салат" },
  { rus: "das Fleisch", de: "мясо" },
  { rus: "der Fisch", de: "рыба" },
  { rus: "das Gemüse", de: "овощи" },
  { rus: "die Frucht", de: "фрукт" },
  { rus: "der Nachtisch", de: "десерт" },
  { rus: "das Getränk", de: "напиток" },
  { rus: "der Tee", de: "чай" },
  { rus: "der Kaffee", de: "кофе" },
  { rus: "das Wasser", de: "вода" },
  { rus: "der Saft", de: "сок" },
  { rus: "die Milch", de: "молоко" },
  { rus: "der Wein", de: "вино" },
  { rus: "das Bier", de: "пиво" },
  { rus: "die Limonade", de: "лимонад" },
  { rus: "die Zucker", de: "сахар" },
  { rus: "das Salz", de: "соль" },
  { rus: "der Pfeffer", de: "перец" },
  { rus: "die Gewürze", de: "специи" },
  { rus: "die Bratpfanne", de: "сковорода" },
  { rus: "der Topf", de: "кастрюля" },
  { rus: "der Backofen", de: "духовка" },
  { rus: "der Kühlschrank", de: "холодильник" },
  { rus: "der Tisch", de: "стол" },
  { rus: "der Stuhl", de: "стул" },
  { rus: "die Couch", de: "диван" },
  { rus: "der Fernseher", de: "телевизор" },
  { rus: "das Radio", de: "радио" },
  { rus: "die Lampe", de: "лампа" },
  { rus: "das Bild", de: "картина" },
  { rus: "der Spiegel", de: "зеркало" },
  { rus: "die Blume", de: "цветок" },
  { rus: "die Vase", de: "ваза" },
  { rus: "der Teppich", de: "ковер" },
  { rus: "die Uhr", de: "часы" },
  { rus: "der Wecker", de: "будильник" },
  { rus: "das Telefon", de: "телефон" },
  { rus: "der Computer", de: "компьютер" },
  { rus: "das Tablet", de: "планшет" },
  { rus: "die Kamera", de: "камера" },
  { rus: "das Buch", de: "книга" },
  { rus: "die Zeitung", de: "газета" },
  { rus: "das Magazin", de: "журнал" },
  { rus: "der Stift", de: "ручка" },
  { rus: "der Bleistift", de: "карандаш" },
  { rus: "das Papier", de: "бумага" },
  { rus: "das Notizbuch", de: "блокнот" },
  { rus: "die Tasche", de: "сумка" },
  { rus: "der Rucksack", de: "рюкзак" },
  { rus: "die Geldbörse", de: "кошелек" },
  { rus: "der Schlüssel", de: "ключ" },
  { rus: "die Brille", de: "очки" },
  { rus: "der Regenschirm", de: "зонтик" },
  { rus: "die Jacke", de: "куртка" },
  { rus: "der Pullover", de: "свитер" },
  { rus: "die Hose", de: "брюки" },
  { rus: "das Kleid", de: "платье" },
  { rus: "der Anzug", de: "костюм" },
  { rus: "die Schuhe", de: "обувь" },
  { rus: "der Hut", de: "шляпа" },
  { rus: "der Schal", de: "шарф" },
  { rus: "die Handschuhe", de: "перчатки" },
  { rus: "der Schmuck", de: "украшения" },
  { rus: "die Familie", de: "семья" },
  { rus: "der Vater", de: "отец" },
  { rus: "die Mutter", de: "мать" },
  { rus: "der Sohn", de: "сын" },
  { rus: "die Tochter", de: "дочь" },
  { rus: "die Eltern", de: "родители" },
  { rus: "der Bruder", de: "брат" },
  { rus: "die Schwester", de: "сестра" },
  { rus: "der Großvater", de: "дедушка" },
  { rus: "die Großmutter", de: "бабушка" },
  { rus: "der Onkel", de: "дядя" },
  { rus: "die Tante", de: "тётя" },
  { rus: "der Cousin", de: "двоюродный брат" },
  { rus: "die Cousine", de: "двоюродная сестра" },
  { rus: "der Neffe", de: "племянник" },
  { rus: "die Nichte", de: "племянница" },
  { rus: "der Ehemann", de: "муж" },
  { rus: "die Ehefrau", de: "жена" },
  { rus: "der Verlobte", de: "жених" },
  { rus: "die Verlobte", de: "невеста" },
  { rus: "die Hochzeit", de: "свадьба" },
  { rus: "die Scheidung", de: "развод" },
  { rus: "das Baby", de: "младенец" },
  { rus: "das Kind", de: "ребенок" },
  { rus: "der Teenager", de: "подросток" },
  { rus: "der Erwachsene", de: "взрослый" },
  { rus: "der Senior", de: "пожилой человек" },
  { rus: "die Geburt", de: "рождение" },
  { rus: "die Adoption", de: "усыновление" },
  { rus: "der Kinderwagen", de: "коляска" },
  { rus: "die Windel", de: "подгузник" },
  { rus: "das Spielzeug", de: "игрушка" },
  { rus: "die Schule", de: "школа" },
  { rus: "der Lehrer", de: "учитель" },
  { rus: "die Lehrerin", de: "учительница" },
  { rus: "das Klassenzimmer", de: "класс" },
  { rus: "die Klasse", de: "школьный класс" },
  { rus: "der Stundenplan", de: "расписание" },
  { rus: "das Fach", de: "предмет" },
  { rus: "die Prüfung", de: "экзамен" },
  { rus: "die Hausaufgaben", de: "домашние задания" },
  { rus: "die Schultasche", de: "школьная сумка" },
  { rus: "der Schulranzen", de: "ранец" },
  { rus: "der Schulweg", de: "путь в школу" },
  { rus: "der Pausenhof", de: "школьный двор" },
  { rus: "die Ferien", de: "каникулы" },
  { rus: "der Schulabschluss", de: "окончание школы" },
  { rus: "die Universität", de: "университет" },
  { rus: "das Studium", de: "учеба" },
  { rus: "die Vorlesung", de: "лекция" },
  { rus: "der Student", de: "студент" },
  { rus: "die Studentin", de: "студентка" },
  { rus: "die Prüfung", de: "экзамен" },
  { rus: "das Semester", de: "семестр" },
  { rus: "die Bibliothek", de: "библиотека" },
  { rus: "das Studienfach", de: "специальность" },
  { rus: "der Abschluss", de: "окончание" },
  { rus: "die Note", de: "отметка" },
  { rus: "das Diplom", de: "диплом" },
  { rus: "die Forschung", de: "исследование" },
  { rus: "der Wissenschaftler", de: "ученый" },
  { rus: "die Wissenschaftlerin", de: "ученая" },
  { rus: "die Entdeckung", de: "открытие" },
  { rus: "die Innovation", de: "инновация" },
  { rus: "die Technologie", de: "технология" },
  { rus: "der Computer", de: "компьютер" },
  { rus: "das Internet", de: "интернет" },
  { rus: "die Software", de: "программное обеспечение" },
  { rus: "der Code", de: "код" },
  { rus: "die Programmiersprache", de: "язык программирования" },
  { rus: "der Algorithmus", de: "алгоритм" },
  { rus: "die Daten", de: "данные" },
  { rus: "die Cloud", de: "облачное хранилище" },
  { rus: "das Smartphone", de: "смартфон" },
  { rus: "die App", de: "приложение" },
  { rus: "die sozialen Medien", de: "социальные сети" },
  { rus: "der Benutzer", de: "пользователь" },
  { rus: "die Benutzerin", de: "пользовательница" },
  { rus: "das Passwort", de: "пароль" },
  { rus: "die Sicherheit", de: "безопасность" },
  { rus: "die Umwelt", de: "окружающая среда" },
  { rus: "der Umweltschutz", de: "охрана окружающей среды" },
  { rus: "die Erde", de: "Земля (планета)" },
  { rus: "die Luft", de: "воздух" },
  { rus: "das Wasser", de: "вода" },
  { rus: "der Wald", de: "лес" },
  { rus: "die Pflanze", de: "растение" },
  { rus: "das Tier", de: "животное" },
  { rus: "die Art", de: "вид" },
  { rus: "die Bedrohung", de: "угроза" },
  { rus: "die Ressource", de: "ресурс" },
  { rus: "das Recycling", de: "переработка" },
  { rus: "der Klimawandel", de: "изменение климата" },
  { rus: "die Energie", de: "энергия" },
  { rus: "die Sonnenenergie", de: "солнечная энергия" },
  { rus: "die Windenergie", de: "ветровая энергия" },
  { rus: "die Atomenergie", de: "атомная энергия" },
  { rus: "das Elektroauto", de: "электромобиль" },
  { rus: "der Fahrradweg", de: "велосипедная дорожка" },
  { rus: "die Fußgängerzone", de: "пешеходная зона" },
  { rus: "der Verkehr", de: "движение" },
  { rus: "das Auto", de: "автомобиль" },
  { rus: "der Bus", de: "автобус" },
  { rus: "die Straßenbahn", de: "трамвай" },
  { rus: "die U-Bahn", de: "метро" },
  { rus: "das Flugzeug", de: "самолет" },
  { rus: "der Zug", de: "поезд" },
  { rus: "das Schiff", de: "корабль" },
  { rus: "die Haltestelle", de: "остановка" },
  { rus: "der Fahrplan", de: "расписание" },
  { rus: "die Fahrkarte", de: "билет" },
  { rus: "der Flughafen", de: "аэропорт" },
  { rus: "der Bahnhof", de: "вокзал" },
  { rus: "die Reise", de: "путешествие" },
  { rus: "die Unterkunft", de: "размещение" },
  { rus: "die Pension", de: "пансион" },
  { rus: "die Jugendherberge", de: "молодежная гостиница" },
  { rus: "die Ferienwohnung", de: "квартира на время отпуска" },
  { rus: "die Campingplatz", de: "кемпинг" },
  { rus: "die Sehenswürdigkeit", de: "достопримечательность" },
  { rus: "das Denkmal", de: "памятник" },
  { rus: "die Brücke", de: "мост" },
  { rus: "der Park", de: "парк" },
  { rus: "der Zoo", de: "зоопарк" },
  { rus: "das Museum", de: "музей" },
  { rus: "die Galerie", de: "галерея" },
  { rus: "die Ausstellung", de: "выставка" },
  { rus: "das Konzert", de: "концерт" },
  { rus: "das Theater", de: "театр" },
  { rus: "der Film", de: "фильм" },
  { rus: "die Musik", de: "музыка" },
  { rus: "das Lied", de: "песня" },
  { rus: "der Sänger", de: "певец" },
  { rus: "die Sängerin", de: "певица" },
  { rus: "das Instrument", de: "инструмент" },
  { rus: "die Gitarre", de: "гитара" },
  { rus: "das Klavier", de: "фортепиано" },
  { rus: "das Schlagzeug", de: "ударные" },
  { rus: "die Stimme", de: "голос" },
  { rus: "der Rhythmus", de: "ритм" },
  { rus: "der Text", de: "текст" },
  { rus: "die Melodie", de: "мелодия" },
  { rus: "das Konzert", de: "концерт" },
  { rus: "die Party", de: "вечеринка" },
  { rus: "die Veranstaltung", de: "мероприятие" },
  { rus: "die Einladung", de: "приглашение" },
  { rus: "der Gast", de: "гость" },
  { rus: "das Geschenk", de: "подарок" },
  { rus: "der Geburtstag", de: "день рождения" },
  { rus: "das Jubiläum", de: "юбилей" },
  { rus: "die Feier", de: "праздник" },
  { rus: "die Dekoration", de: "украшение" },
  { rus: "die Ballons", de: "воздушные шары" },
  { rus: "die Kerzen", de: "свечи" },
  { rus: "die Torte", de: "торт" },
  { rus: "der Champagner", de: "шампанское" },
  { rus: "das Feuerwerk", de: "фейерверк" },
  { rus: "der Karneval", de: "карнавал" },
  { rus: "die Kostümparty", de: "вечеринка в костюмах" },
  { rus: "die Maske", de: "маска" },
];
export const a1Sentence: IWord[] = [
  { rus: "Guten Tag", de: "Добрый день" },
  { rus: "Hallo", de: "Привет" },
  { rus: "Auf Wiedersehen", de: "До свидания" },
  { rus: "Bitte", de: "Пожалуйста" },
  { rus: "Danke", de: "Спасибо" },
  { rus: "Ja", de: "Да" },
  { rus: "Nein", de: "Нет" },
  { rus: "Entschuldigung", de: "Извините" },
  { rus: "Wie geht es Ihnen?", de: "Как вы? (формально)" },
  { rus: "Wie geht's?", de: "Как дела? (неформально)" },
  { rus: "Ich heiße...", de: "Меня зовут..." },
  { rus: "Wie ist Ihr Name?", de: "Как вас зовут? (формально)" },
  { rus: "Wie heißt du?", de: "Как тебя зовут? (неформально)" },
  { rus: "Woher kommen Sie?", de: "Откуда вы? (формально)" },
  { rus: "Woher kommst du?", de: "Откуда ты? (неформально)" },
  { rus: "Ich komme aus...", de: "Я из..." },
  { rus: "Sprechen Sie Deutsch?", de: "Говорите по-немецки? (формально)" },
  { rus: "Sprichst du Deutsch?", de: "Говоришь по-немецки? (неформально)" },
  { rus: "Ich verstehe nicht", de: "Я не понимаю" },
  { rus: "Können Sie das wiederholen?", de: "Можете повторить? (формально)" },
  { rus: "Kannst du das wiederholen?", de: "Можешь повторить? (неформально)" },
  { rus: "Wie viel kostet das?", de: "Сколько это стоит?" },
  { rus: "Wo ist die Toilette?", de: "Где туалет?" },
  { rus: "Ich habe Hunger", de: "Я голоден" },
  { rus: "Ich habe Durst", de: "Я хочу пить" },
  { rus: "Wie spät ist es?", de: "Который час?" },
  { rus: "Was ist das?", de: "Что это?" },
  { rus: "Wo ist der Bahnhof?", de: "Где железнодорожный вокзал?" },
  { rus: "In der Nähe", de: "Вблизи" },
  { rus: "Weit", de: "Далеко" },
  { rus: "Links", de: "Слева" },
  { rus: "Rechts", de: "Справа" },
  { rus: "Hilfe!", de: "Помощь!" },
  { rus: "Ich brauche Hilfe", de: "Мне нужна помощь" },
  { rus: "Das ist schön", de: "Это красиво" },
  { rus: "Das ist interessant", de: "Это интересно" },
  { rus: "Ich liebe dich", de: "Я тебя люблю" },
  { rus: "Gute Reise!", de: "Счастливого пути!" },
  { rus: "Ich bin müde", de: "Я устал(а)" },
  { rus: "Ich bin froh", de: "Я рад(а)" },
  { rus: "Das ist teuer", de: "Это дорого" },
  { rus: "Das ist billig", de: "Это дешево" },
  { rus: "Kann ich mit Karte zahlen?", de: "Могу ли я заплатить картой?" },
  { rus: "Was machst du beruflich?", de: "Кем ты работаешь?" },
  { rus: "Ich bin Student(in)", de: "Я студент(ка)" },
  { rus: "Mein Geburtstag ist am...", de: "Мой день рождения ... (дата)" },
  { rus: "Herzlichen Glückwunsch!", de: "С днем рождения! (Поздравляю!)" },
  { rus: "Wo ist die U-Bahn-Station?", de: "Где станция метро?" },
  { rus: "Ich habe eine Frage", de: "У меня есть вопрос" },
  { rus: "Das verstehe ich nicht", de: "Я не понимаю это" },
  { rus: "Was machst du gerne?", de: "Что ты любишь делать?" },
  { rus: "Ich mag Musik hören", de: "Мне нравится слушать музыку" },
  { rus: "Wie viel kostet das Ticket?", de: "Сколько стоит билет?" },
  { rus: "Ich bin hier neu", de: "Я здесь новенький(ая)" },
  { rus: "Kannst du mir helfen?", de: "Ты можешь мне помочь?" },
  { rus: "Ich habe eine Idee", de: "У меня есть идея" },
  {
    rus: "Das ist mein Freund/ meine Freundin",
    de: "Это мой друг/моя подруга",
  },
  { rus: "Ich bin ein Tourist", de: "Я турист" },
  { rus: "Was machst du am Wochenende?", de: "Что ты делаешь на выходных?" },
  { rus: "Das ist wunderschön", de: "Это прекрасно" },
  { rus: "Wo wohnst du?", de: "Где ты живешь?" },
  { rus: "Ich bin hungrig", de: "Я голоден(а)" },
  {
    rus: "Was machst du gern in deiner Freizeit?",
    de: "Что ты любишь делать в свободное время?",
  },
  { rus: "Wie lange bleibst du hier?", de: "Как долго ты здесь останешься?" },
  { rus: "Das ist nicht weit", de: "Это недалеко" },
  { rus: "Wie findest du die Stadt?", de: "Как тебе город?" },
  { rus: "Ich bin beschäftigt", de: "Я занят(а)" },
  { rus: "Was machst du beruflich?", de: "Чем ты занимаешься по профессии?" },
  { rus: "Ich habe eine Einladung", de: "У меня есть приглашение" },
  { rus: "Ich bin nicht sicher", de: "Я не уверен(а)" },
  { rus: "Das ist einfach", de: "Это просто" },
  { rus: "Ich bin interessiert", de: "Меня это интересует" },
  { rus: "Wie viel kostet das pro Nacht?", de: "Сколько это стоит за ночь?" },
  { rus: "Ich liebe es zu reisen", de: "Я люблю путешествовать" },
  { rus: "Das ist mein Lieblingsbuch", de: "Это моя любимая книга" },
  {
    rus: "Was machst du gerne in deiner Freizeit?",
    de: "Что ты любишь делать в свободное время?",
  },
  { rus: "Das ist zu teuer für mich", de: "Это слишком дорого для меня" },
  {
    rus: "Ich spreche ein bisschen Deutsch",
    de: "Я немного говорю по-немецки",
  },
  { rus: "Das ist sehr interessant", de: "Это очень интересно" },
  { rus: "Wie spät ist es jetzt?", de: "Который час сейчас?" },
  { rus: "Ich bin mit allem einverstanden", de: "Я согласен(а) со всем" },
  { rus: "Das ist meine Telefonnummer", de: "Это мой номер телефона" },
  { rus: "Wo kann ich Geld wechseln?", de: "Где я могу поменять валюту?" },
  { rus: "Ich bin krank", de: "Я болен(а)" },
  { rus: "Das ist mein Auto", de: "Это моя машина" },
  { rus: "Ich freue mich darauf", de: "Я с нетерпением жду" },
  { rus: "Das ist in Ordnung", de: "Всё в порядке" },
  { rus: "Wie alt bist du?", de: "Сколько тебе лет?" },
  { rus: "Ich mag Sport", de: "Мне нравится спорт" },
  { rus: "Das ist sehr nett von dir", de: "Это очень мило с твоей стороны" },
  { rus: "Was machst du morgen?", de: "Что ты будешь делать завтра?" },
  { rus: "Ich bin nicht interessiert", de: "Меня это не интересует" },
  {
    rus: "Das ist mein Freund/ meine Freundin",
    de: "Это мой друг/моя подруга",
  },
  { rus: "Ich bin nicht sicher", de: "Я не уверен(а)" },
  { rus: "Was studierst du?", de: "Что ты изучаешь (по образованию)?" },
  { rus: "Das ist nicht so wichtig", de: "Это не так важно" },
  { rus: "Wie war dein Tag?", de: "Как прошёл твой день?" },
  { rus: "Ich bin hier auf Urlaub", de: "Я здесь в отпуске" },
  { rus: "Das ist richtig", de: "Это верно" },
  { rus: "Ich komme gleich", de: "Я скоро приду" },
  { rus: "Wo kann ich essen gehen?", de: "Где я могу поесть?" },
  { rus: "Das ist zu viel", de: "Это слишком много" },
  { rus: "Wie viel kostet die Fahrkarte?", de: "Сколько стоит билет?" },
  { rus: "Ich habe eine Idee", de: "У меня есть идея" },
  { rus: "Das ist nicht fair", de: "Это нечестно" },
  { rus: "Ich habe meine Tasche verloren", de: "Я потерял(а) свою сумку" },
  { rus: "Das ist wirklich interessant", de: "Это действительно интересно" },
  { rus: "Wie kommst du zur Arbeit?", de: "Как ты добираешься на работу?" },
  {
    rus: "Ich habe eine Einladung zum Abendessen",
    de: "У меня есть приглашение на ужин",
  },
  { rus: "Das ist mein Lieblingsrestaurant", de: "Это мое любимое ресторан" },
  {
    rus: "Kannst du mir den Weg zeigen?",
    de: "Ты можешь мне показать дорогу?",
  },
  { rus: "Ich bin nicht sicher", de: "Я не уверен(а)" },
  {
    rus: "Was machst du gern in deiner Freizeit?",
    de: "Что ты любишь делать в свободное время?",
  },
  { rus: "Das ist zu spät", de: "Это слишком поздно" },
  { rus: "Wie war dein Wochenende?", de: "Как прошёл твой уикенд?" },
  { rus: "Ich liebe es zu kochen", de: "Мне нравится готовить" },
  { rus: "Das ist einfach", de: "Это просто" },
  {
    rus: "Was machst du heute Abend?",
    de: "Что ты будешь делать сегодня вечером?",
  },
  {
    rus: "Ich interessiere mich für Geschichte",
    de: "Меня интересует история",
  },
  { rus: "Das ist zu laut", de: "Это слишком громко" },
  { rus: "Wie geht es deiner Familie?", de: "Как у твоей семьи?" },
  { rus: "Ich lerne Deutsch seit einem Jahr", de: "Я учу немецкий год" },
  { rus: "Das ist nicht schlecht", de: "Это неплохо" },
  {
    rus: "Wie viel kostet das Ticket nach Berlin?",
    de: "Сколько стоит билет в Берлин?",
  },
  {
    rus: "Ich freue mich auf das Wochenende",
    de: "Я жду с нетерпением выходных",
  },
  { rus: "Das ist mein Hobby", de: "Это мое хобби" },
  { rus: "Kannst du mir helfen?", de: "Ты можешь мне помочь?" },
  { rus: "Wie viel kostet das Auto?", de: "Сколько стоит машина?" },
  { rus: "Das ist mein Traum", de: "Это моя мечта" },
  { rus: "Wie geht es deiner Mutter?", de: "Как у твоей мамы?" },
  { rus: "Ich habe meinen Schlüssel vergessen", de: "Я забыл(а) свой ключ" },
  { rus: "Das ist nicht weit", de: "Это не далеко" },
  { rus: "Wie spät ist es jetzt?", de: "Который час сейчас?" },
  { rus: "Ich habe eine Frage", de: "У меня есть вопрос" },
  { rus: "Das ist mein Zimmer", de: "Это моя комната" },
  { rus: "Wie viel kostet das Kleid?", de: "Сколько стоит платье?" },
  { rus: "Ich bin einverstanden", de: "Я согласен(а)" },
  { rus: "Das ist zu kalt", de: "Это слишком холодно" },
  { rus: "Wie war deine Reise?", de: "Как прошло твое путешествие?" },
  { rus: "Ich habe meinen Pass verloren", de: "Я потерял(а) свой паспорт" },
  { rus: "Das ist mein Plan", de: "Это мой план" },
  { rus: "Wie viel kostet das Abendessen?", de: "Сколько стоит ужин?" },
  { rus: "Ich interessiere mich für Kunst", de: "Меня интересует искусство" },
  { rus: "Das ist zu warm", de: "Это слишком тепло" },
  { rus: "Wie geht es deinem Vater?", de: "Как у твоего отца?" },
  { rus: "Ich habe Zeit", de: "У меня есть время" },
  { rus: "Das ist nicht so wichtig", de: "Это не так важно" },
  { rus: "Wie viel kostet die Fahrt?", de: "Сколько стоит поездка?" },
  { rus: "Ich mag Filme", de: "Мне нравятся фильмы" },
  { rus: "Das ist zu viel", de: "Это слишком много" },
  { rus: "Wie war deine Woche?", de: "Как прошла твоя неделя?" },
  { rus: "Ich bin aufgeregt", de: "Я взволнован(а)" },
  { rus: "Das ist mein Lieblingssong", de: "Это моя любимая песня" },
  {
    rus: "Wie viel kostet das Hotelzimmer?",
    de: "Сколько стоит номер в отеле?",
  },
  { rus: "Ich bin gestresst", de: "Я в стрессе" },
  { rus: "Das ist zu einfach", de: "Это слишком просто" },
  { rus: "Wie geht es deinem Bruder?", de: "Как у твоего брата?" },
  { rus: "Ich freue mich darauf", de: "Я с нетерпением жду" },
  { rus: "Das ist mein Glückstag", de: "Это мой счастливый день" },
  { rus: "Wie viel kostet die Stunde?", de: "Сколько стоит час?" },
  { rus: "Ich bin nicht interessiert", de: "Меня это не интересует" },
  { rus: "Das ist nicht mein Problem", de: "Это не моя проблема" },
  { rus: "Wie war deine Nacht?", de: "Как ты спал(а) ночью?" },
  { rus: "Ich bin beschäftigt", de: "Я занят(а)" },
  { rus: "Das ist zu schwer", de: "Это слишком сложно" },
  { rus: "Wie viel kostet das Frühstück?", de: "Сколько стоит завтрак?" },
  { rus: "Ich mag Tiere", de: "Мне нравятся животные" },
  { rus: "Das ist zu langsam", de: "Это слишком медленно" },
  { rus: "Wie geht es deiner Schwester?", de: "Как у твоей сестры?" },
  { rus: "Ich bin neugierig", de: "Я любопытен(а)" },
  { rus: "Das ist nicht fair", de: "Это нечестно" },
  { rus: "Wie viel kostet der Flug?", de: "Сколько стоит билет на самолет?" },
  { rus: "Ich bin verärgert", de: "Я раздражен(а)" },
  { rus: "Das ist zu laut", de: "Это слишком громко" },
  { rus: "Wie viel kostet die Pizza?", de: "Сколько стоит пицца?" },
  { rus: "Ich bin nicht interessiert", de: "Меня это не интересует" },
  { rus: "Das ist zu teuer", de: "Это слишком дорого" },
  { rus: "Wie geht es deinem Freund?", de: "Как у твоего друга?" },
  { rus: "Ich bin froh", de: "Я рад(а)" },
  { rus: "Das ist mein Lieblingssport", de: "Это мой любимый вид спорта" },
  { rus: "Wie viel kostet der Eintritt?", de: "Сколько стоит вход?" },
  { rus: "Ich bin verwirrt", de: "Я запутался(ась)" },
  { rus: "Das ist zu kurz", de: "Это слишком коротко" },
  { rus: "Wie geht es deiner Mutter?", de: "Как у твоей мамы?" },
  {
    rus: "Ich habe eine Überraschung für dich",
    de: "У меня есть сюрприз для тебя",
  },
  { rus: "Das ist nicht einfach", de: "Это не просто" },
  { rus: "Wie viel kostet das Bier?", de: "Сколько стоит пиво?" },
  {
    rus: "Wie viel kostet der Zutritt zum Schwimmbad?",
    de: "Сколько стоит вход в бассейн?",
  },
  {
    rus: "Ich bin beeindruckt von deiner Leistung",
    de: "Я впечатлен(а) твоими достижениями",
  },
  { rus: "Das ist zu nahe", de: "Это слишком близко" },
  {
    rus: "Wie viel kostet der Eintritt zum Vergnügungspark?",
    de: "Сколько стоит вход в парк развлечений?",
  },
  {
    rus: "Ich bin verärgert über diese Situation",
    de: "Эта ситуация меня раздражает",
  },
  {
    rus: "Das ist zu spät für die Veranstaltung",
    de: "Это слишком поздно для мероприятия",
  },
  {
    rus: "Wie viel kostet die Stadtrundfahrt?",
    de: "Сколько стоит экскурсия по городу?",
  },
  { rus: "Ich bin glücklich", de: "Я счастлив(а)" },
  { rus: "Das ist zu früh am Morgen", de: "Это слишком рано утром" },
  {
    rus: "Wie viel kostet die Schifffahrt?",
    de: "Сколько стоит поездка на корабле?",
  },
  {
    rus: "Ich bin neugierig auf das Ergebnis",
    de: "Я любопытен(а) по поводу результата",
  },
  { rus: "Das ist zu spät am Abend", de: "Это слишком поздно вечером" },
  {
    rus: "Wie viel kostet die Kutschfahrt?",
    de: "Сколько стоит поездка на карете?",
  },
  { rus: "Ich bin begeistert von der Idee", de: "Я в восторге от этой идеи" },
  {
    rus: "Das ist zu kurz für einen Urlaub",
    de: "Это слишком короткий отпуск",
  },
  {
    rus: "Wie viel kostet der Eintritt zum Aquarium?",
    de: "Сколько стоит вход в аквариум?",
  },
  { rus: "Ich bin erschöpft von der Arbeit", de: "Я изнурен(а) от работы" },
  { rus: "Das ist zu langweilig", de: "Это слишком скучно" },
  {
    rus: "Wie viel kostet die Zugfahrt?",
    de: "Сколько стоит поездка на поезде?",
  },
  {
    rus: "Ich bin verwirrt über die Anweisungen",
    de: "Я запутался(ась) в инструкциях",
  },
  { rus: "Das ist zu kompliziert für mich", de: "Это слишком сложно для меня" },
  {
    rus: "Wie viel kostet die Flusskreuzfahrt?",
    de: "Сколько стоит круиз по реке?",
  },
  {
    rus: "Ich bin unsicher über meine Entscheidung",
    de: "Я неуверен(а) в своем решении",
  },
  { rus: "Das ist zu einfach für dich", de: "Это слишком просто для тебя" },
  {
    rus: "Wie viel kostet der Eintritt zum Freizeitpark?",
    de: "Сколько стоит вход в парк развлечений?",
  },
  { rus: "Ich bin beunruhigt über die Zukunft", de: "Я беспокоюсь о будущем" },
  { rus: "Das ist zu schwer zu verstehen", de: "Это слишком трудно понять" },
  {
    rus: "Wie viel kostet die Miete für das Ferienhaus?",
    de: "Сколько стоит аренда коттеджа?",
  },
  {
    rus: "Ich bin erstaunt über deine Fähigkeiten",
    de: "Я удивлен(а) твоими способностями",
  },
  { rus: "Das ist zu leicht zu vergessen", de: "Это слишком легко забыть" },
  {
    rus: "Wie viel kostet der Zutritt zum Schwimmbad?",
    de: "Сколько стоит вход в бассейн?",
  },
  {
    rus: "Ich bin beeindruckt von deiner Leistung",
    de: "Я впечатлен(а) твоими достижениями",
  },
  { rus: "Das ist zu nahe", de: "Это слишком близко" },
  {
    rus: "Wie viel kostet der Eintritt zum Vergnügungspark?",
    de: "Сколько стоит вход в парк развлечений?",
  },
  {
    rus: "Ich bin verärgert über diese Situation",
    de: "Эта ситуация меня раздражает",
  },
  {
    rus: "Das ist zu spät für die Veranstaltung",
    de: "Это слишком поздно для мероприятия",
  },
  {
    rus: "Wie viel kostet die Stadtrundfahrt?",
    de: "Сколько стоит экскурсия по городу?",
  },
  { rus: "Ich bin glücklich", de: "Я счастлив(а)" },
  { rus: "Das ist zu früh am Morgen", de: "Это слишком рано утром" },
  {
    rus: "Wie viel kostet die Schifffahrt?",
    de: "Сколько стоит поездка на корабле?",
  },
  {
    rus: "Ich bin neugierig auf das Ergebnis",
    de: "Я любопытен(а) по поводу результата",
  },
  { rus: "Das ist zu spät am Abend", de: "Это слишком поздно вечером" },
  {
    rus: "Wie viel kostet die Kutschfahrt?",
    de: "Сколько стоит поездка на карете?",
  },
  { rus: "Ich bin begeistert von der Idee", de: "Я в восторге от этой идеи" },
  {
    rus: "Das ist zu kurz für einen Urlaub",
    de: "Это слишком короткий отпуск",
  },
  {
    rus: "Wie viel kostet der Eintritt zum Aquarium?",
    de: "Сколько стоит вход в аквариум?",
  },
  { rus: "Ich bin erschöpft von der Arbeit", de: "Я изнурен(а) от работы" },
  { rus: "Das ist zu langweilig", de: "Это слишком скучно" },
  {
    rus: "Wie viel kostet die Zugfahrt?",
    de: "Сколько стоит поездка на поезде?",
  },
  {
    rus: "Ich bin verwirrt über die Anweisungen",
    de: "Я запутался(ась) в инструкциях",
  },
  { rus: "Das ist zu kompliziert für mich", de: "Это слишком сложно для меня" },
  {
    rus: "Wie viel kostet die Flusskreuzfahrt?",
    de: "Сколько стоит круиз по реке?",
  },
  {
    rus: "Ich bin unsicher über meine Entscheidung",
    de: "Я неуверен(а) в своем решении",
  },
  { rus: "Das ist zu einfach für dich", de: "Это слишком просто для тебя" },
  {
    rus: "Wie viel kostet der Eintritt zum Freizeitpark?",
    de: "Сколько стоит вход в парк развлечений?",
  },
  { rus: "Ich bin beunruhigt über die Zukunft", de: "Я беспокоюсь о будущем" },
  { rus: "Das ist zu schwer zu verstehen", de: "Это слишком трудно понять" },
  {
    rus: "Wie viel kostet die Miete für das Ferienhaus?",
    de: "Сколько стоит аренда коттеджа?",
  },
  {
    rus: "Ich bin erstaunt über deine Fähigkeiten",
    de: "Я удивлен(а) твоими способностями",
  },
  { rus: "Das ist zu leicht zu vergessen", de: "Это слишком легко забыть" },
];

//готовые объекты для компонента
export type IWordsLesson = { name: string; data: IWord[] };
export const lesson1Words: IWordsLesson[] = [
  { name: "Слова", data: lesson1WordsArr },
  { name: "Предложения", data: lesson1sentence },
  { name: "Предметы существительные", data: roomItems },
  { name: "Фразы предметы в комнате", data: lesson1_1sentence },
  { name: "Cтоловые предметы", data: lesson1_1WordsArr },
  { name: "А-1 Слова", data: a1Words },
  { name: "А-1 Предложения", data: a1Sentence },
];

export const lesson6Words: IWordsLesson[] = [
  { name: "Предложения", data: lesson6sentence },
];

export const lesson7Words: IWordsLesson[] = [
  { name: "Слова", data: lesson7WordArr },
  { name: "Предложения", data: lesson7Sentence },
];

export const lesson8Words: IWordsLesson[] = [
  { name: "Задать вопросы", data: lesson8_1Sentence },
  { name: "Вопросы с вопросительным словом", data: lesson8_2Sentence },
];
